### ISSUE TITLE
add governanceCycle number input to action so submitoors can decide when an action should be executed

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/nance-interface#104]
Default to current

Maybe something like below?

![Image](https://github.com/nance-eth/nance-interface/assets/83923290/81b971e3-994f-4b89-b6bc-643386aa9de2)

**Comment by jigglyjams** [comment]
Use case:

TokenTable proposal that requested payouts in 3 stages

This could be implemented with 3 different payouts that specify future governance cycles for the start date of the payout

**Comment by twodam** [comment]
moved to https://github.com/nance-eth/nance-ts/issues/103
