### ISSUE TITLE
Merge MoonDAO style local cache into nance.app

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/nance-interface#145]
https://github.com/nance-eth/MoonDAO-app/blob/main/ui/components/nance/ProposalLocalCache.tsx

has nice bar at top that says when the cache was saved. also allows for uuid based caching so you can edit multiple proposals and have local cache (only one `new` one though, could be improved upon)

![Image](https://github.com/user-attachments/assets/9a6d22f5-5bc0-4c7c-9b84-a010517fad74)

![Image](https://github.com/user-attachments/assets/6018c860-cbe4-4491-a9af-f0f44154ff98)

**Comment by twodam** [comment]
implemented by https://github.com/nance-eth/nance-interface/commit/5818268d101bd1901d1c68c460f8f04cc987c313
