### ISSUE TITLE
display milestone poll from action

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/nance-interface#148]
See figma screens
https://www.figma.com/design/dRkVG0sd1JeYjmkJCfplfF/Milestone-Actions?node-id=16-2&t=p1v1jjpCEsXKZLH8-0

**Comment by jigglyjams** [comment]
![Image](https://github.com/user-attachments/assets/ed8923b3-d4ab-4fc8-a1c9-933547447c12)

**Comment by jigglyjams** [comment]
then show results of poll if they exist

**Comment by twodam** [comment]
> then show results of poll if they exist

is this necessary? show results after proposal pass or during polling?

**Comment by jigglyjams** [comment]
lets start with just a link to the poll and see if we need to show the results
