### ISSUE TITLE
admin mode to change proposal status

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/nance-interface#157]

**Comment by jigglyjams** [comment]
supported by api now https://github.com/nance-eth/nance-ts/blob/607e3852b929c80831d5c83bc9d7693380df9f27/src/api/routes/space/proposal.ts#L112

TODO: update docs

**Comment by jigglyjams** [comment]
something like this in the UI would be nice ![Image](https://github.com/user-attachments/assets/68a1d3a1-67d0-4980-b7b5-81f64220daea)

**Comment by twodam** [comment]
implemented by https://github.com/nance-eth/nance-interface/commit/e20cc544f169d61e9003fc1ad0b046f52358b18e
