### ISSUE TITLE
Redesign new proposal page

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/nance-interface#17]
- [x] Simplify the page style, remove blank div
- [x] Move new page button up to SiteNav
- [x] Support attach action, for example: add payout, add reserve, edit metadata, custom (multisig) transaction. (good inspiration https://daodao.zone/dao/juno1j6glql3xmrcnga0gytecsucq3kd88jexxamxg3yn2xnqhunyvflqr7lxx3/proposals/create and https://abi.ninja/0xFFdD70C318915879d5192e8a0dcbFcB0285b3C98/mainnet?functions=burnTokensOf%2CdistributeReservedTokensOf)

**Comment by jigglyjams** [comment]
![Image](https://user-images.githubusercontent.com/83923290/227622599-e6f467b4-1a7a-4142-b557-f87e2a837c6f.png)

**Comment by twodam** [comment]
support decimal and float point number in uint256 input, for better readability
