### ISSUE TITLE
Better GC search/selector on mobile

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/nance-interface#18]
It is difficult to go to a different governanceCycle using this search drop down menu while on mobile. Maybe we just disable it on mobile for now and make it a regular drop down

**Comment by twodam** [comment]
![Image](https://github.com/nance-eth/nance-interface/assets/103885077/68311d90-5ba2-47d0-b95e-a91c4498f9a4)

I updated the search bar and cycle selector, is this still an issue?

**Comment by jigglyjams** [comment]
lgtm
