### ISSUE TITLE
Proposals navigator

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/nance-interface#20]
Simple one: add button to go to next proposal
Complex one: Cmd+K to search

![Image](https://user-images.githubusercontent.com/103885077/230099248-46b6f975-f1a2-4848-a7e9-7e31b47ef340.png)

**Comment by twodam** [comment]
fixed by https://github.com/nance-eth/nance-interface/commit/cf9d8814a792315a1e3a56223dd2ee8a0df43760

![image](https://user-images.githubusercontent.com/103885077/236598284-e0752193-0216-4700-90e1-f9291a4f27e5.png)
