### ISSUE TITLE
delegation pop up doesnt dismiss

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/nance-interface#23]
![Image](https://user-images.githubusercontent.com/83923290/229248549-1a2381ae-7425-486d-8ea6-c1fd4f971e98.png)

**Comment by jigglyjams** [comment]
https://github.com/nance-eth/nance-interface/commit/5da4c16dc34593a6df6978091c8bb82365269f25

**Comment by twodam** [comment]
Click to expand voter/delegator profile in sidebar

**Comment by twodam** [comment]
fixed by 161da86e9feaf7b969ff501cf503577ee56b188b
