### ISSUE TITLE
Proposal drafts (private/public)

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/nance-interface#25]
UI Improvement

- pin personal drafts on top
- display on Current and Next cycle

**Comment by jigglyjams** [comment]
Will use local storage so we dont have to have the user sign a message to see private drafts

**Comment by twodam** [comment]
Draft database which have no access control, DoS attack?
Limit it to 100 proposals? So we don't affect other db?
 
Save drafts automatically to the Nance Dolt db.

**Comment by twodam** [comment]
SIWE? session?
<img width="470" alt="image" src="https://github.com/nance-eth/nance-interface/assets/103885077/aabd18ac-975f-4fec-b9e0-2da9297ec273">

**Comment by jigglyjams** [comment]
```
{
  "success": true,
  "data": {
    "proposalInfo": {
      "proposalIdPrefix": "JBP-",
      "minTokenPassingAmount": 80000000
    },
    "proposals": [],
    "privateDrafts": [],
  }
}
```

**Comment by jigglyjams** [comment]
make multiple requests for next cycle or add a flag for a single request?

**Comment by twodam** [comment]
fixed by https://github.com/nance-eth/nance-interface/commit/c72090100fef780a731422ba0e30f895e76c893f
