### ISSUE TITLE
Editable payout list in reconfiguration

### ISSUE THREAD

**Issue by twodam** [nance-eth/nance-interface#29]
Allow bookkeeper to manually modify payout list before submitting reconfiguration list. This will modify payouts in nance db.

I'm not sure about this, can we automate this with our WIP proposal metadata? @jigglyjams 

<img width="726" alt="image" src="https://user-images.githubusercontent.com/103885077/230073525-01737374-96a2-4380-b7e6-5ca21f2cdeaa.png">

**Comment by jigglyjams** [comment]
This should be done at another level:

spaceOwners should be able to edit payouts from a proposal that has already entered voting in the case where a mistake was made or something changed last minute. this could be use maliciously but will also provide the ability to still use the queue transfer when something went wrong and seems worthwhile trade off to me
