### ISSUE TITLE
import/paste markdown into editor

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/nance-interface#32]
![Image](https://user-images.githubusercontent.com/83923290/232131347-e33656ca-bc52-4b90-9200-e4c7c16ee03f.png)

Should be quite easy to support drag and drop of markdown
https://www.tiny.cloud/docs/configure/file-image-upload/

**Comment by twodam** [comment]
fixed by ab4faf3531405945203f28a70621ae2f96bc7bb0
