### ISSUE TITLE
Show proposal links in metadata box

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/nance-interface#35]
![Image](https://user-images.githubusercontent.com/83923290/234469234-43111d57-0425-434d-b47f-917bc0735192.png)

**Comment by twodam** [comment]
fixed ipfs link on https://github.com/nance-eth/nance-interface/commit/14b11067d41375ed8f49f50f9e9652d3f6321b80
it will display Discussion, Snapshot and IPFS link if they are not empty.
