### ISSUE TITLE
Support delete proposal

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/nance-interface#5]

**Comment by twodam** [comment]
who will be able to delete the proposal?

**Comment by jigglyjams** [comment]
See https://jbdao-org-git-delete-proposal-juicetool.vercel.app/s/waterbox/edit?proposalId=16c598dc936a420885e8bb7c64caec9c for example

**Comment by jigglyjams** [comment]
https://github.com/nance-eth/nance-interface/commit/cb163d2a51357fa38bbcec598abae6f08dcd3b83
