### ISSUE TITLE
governor contractor submission (bananapus)

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/nance-interface#53]

**Comment by jigglyjams** [comment]
- [ ] on governorAddress, hide safe nonce field
- [ ] onSubmit will submit to that address instead of safe api
- [ ] governor submit hook

**Comment by jigglyjams** [comment]
I made [this repo](https://github.com/jigglyjams/governor-deploy) to deploy a goerli governor and voting NFT

you could deploy that or use the one I have already set up

**Currently setup:**
* goerli governor deployed at [0xbEAf4476eC398A9B613FCEFdAD6E79B4C9e61B1B](https://goerli.etherscan.io/address/0xbEAf4476eC398A9B613FCEFdAD6E79B4C9e61B1B)
* Voting based on this NFT [0x3f72FcFfeE14873882247381DebACEF967CFBE33](https://goerli.etherscan.io/address/0x3f72FcFfeE14873882247381DebACEF967CFBE33) (can mint on etherscan then delegate to test)
* has a tally setup here: https://www.tally.xyz/gov/phoenix-project
* Voting period of 22 minutes for easy testing
* The governor is the owner of this juicebox project https://goerli.juicebox.money/v2/p/1098
---
I was able to reconfigure the juicebox project as shown here

https://www.tally.xyz/gov/phoenix-project/proposal/114883278985841061977609265319431487007759152428078519325810731928566899908181

https://goerli.etherscan.io/tx/0x507bf6040fefd99d922d265b35f3c9f840efe16da2a9c409d997276c9fa8768f#eventlog

**Comment by twodam** [comment]
working PR: https://github.com/nance-eth/nance-interface/pull/110
deployment: https://jbdao-rerejtjl4-juicetool.vercel.app/
