### ISSUE TITLE
Tooltip about actions

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/nance-interface#61]
![Image](https://user-images.githubusercontent.com/83923290/248971119-c2e1772b-6f69-4db5-8c34-0ebf508b7335.jpeg)

**Comment by twodam** [comment]
![Image](https://github.com/nance-eth/nance-interface/assets/103885077/b82c9726-cb01-4510-ae54-c4723ba0c9b5)

* hide field type for payout and transfer actions
* add tooltip info for some fields
