### ISSUE TITLE
Session issue with WalletConnect V2

### ISSUE THREAD

**Issue by twodam** [nance-eth/nance-interface#68]
![Image](https://github.com/nance-eth/nance-interface/assets/103885077/f65c9c4f-25eb-4a51-8b2a-2b2997a6bf2b)

address logged in are not matched with the one connected wallet through WalletConnect V2

**Comment by jigglyjams** [comment]
Lets make it so when you switch wallet it logs out of the previous one (maybe deletes the cookie as well?)

**Comment by jigglyjams** [comment]
resolved with https://github.com/nance-eth/nance-interface/commit/b01572b006a0e9bab2f2e027079cef751a53f25e
