### ISSUE TITLE
integrate tenderly simulation on frontend

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/nance-interface#72]
nance-api has endpoints to get a customTransaction by uuid and simulate with tenderly api

we may be better off simulating from frontend so users can change the transaction if they see it will fail before submitting

something to think about

**Comment by twodam** [comment]
- [ ] useTenderlySimulation hook, option to skip
- [ ] can run simulation on each custom transaction
- [ ] warn user that some transaction may failed, provide them the simulation links
