### ISSUE TITLE
Single use buttons for proposal save

### ISSUE THREAD

**Issue by twodam** [nance-eth/nance-interface#74]

**Comment by jigglyjams** [comment]
Maybe we just get rid of the descriptions and then the stack will (hopefully) be small enough to not push the page down

**Comment by jigglyjams** [comment]
![Image](https://github.com/nance-eth/nance-interface/assets/83923290/8c8721c4-4a19-46fa-be07-56dcfdf05ff9)

**Comment by jigglyjams** [comment]
looks great!
![Image](https://github.com/user-attachments/assets/07fe0a38-51b1-4090-8e12-62b40fb12133)
