### ISSUE TITLE
Create space UI

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/nance-interface#76]
- [x] login with discord hooks
- [x] discord guild select
- [x] discord channel select
- [x] add bot to server button
- [x] discord user key stored by wallet address
- [x] snapshot space search
- [x] snapshot add nance as author one click
- [x] feedback on snapshot callback
- [x] juicebox project id search
- [x] what to do for calendar?
- [x] cycle length
- [x] duration of each step
- [x] proposal prefix
- [x] temp check threshold
- [x] no jb project? add a safe address or governor contract
~- [ ] pagination (twodam)~
- [x] escape create space name

**Comment by jigglyjams** [comment]
https://jbdao-org-git-create-flow-juicetool.vercel.app/create

**Comment by twodam** [comment]
to split in [steps](https://tailwindui.com/components/application-ui/navigation/steps) maybe. 

![Image](https://github.com/nance-eth/nance-interface/assets/103885077/4be51bf7-0c42-40cc-b0fc-59640b01ff98)

**Comment by jigglyjams** [comment]
lets continue with pagination in a new card
