### ISSUE TITLE
Nance for other client

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/nance-interface#8]
- [ ]  Page for people to create a new Nance space
- [ ]  Function to manage space owner/admin, edit space configuration
- [x]  Page to list all nance spaces
- [x]  Better generic interface for Nance spaces (refactor jbdao.org as template)
- [x]  Better url, for example: `jbdao.org/?overrideSpace=waterbox` => `nance.app/space/waterbox`
- [ ]  Extract nance-sdk and nance-components for self-hosting solution

Discord thread: https://discord.com/channels/1090064637858414633/1090688958066856016

**Comment by jigglyjams** [comment]
WIP:
* hooks and react-hook-form stubbed

https://github.com/nance-eth/nance-interface/tree/create-flow

**Comment by twodam** [comment]
implemented dynamic space with https://github.com/nance-eth/nance-interface/commit/b8f085e3b5f270aa1a6cd6a7540c62d1f63b3a4f
url: https://www.jbdao.org/s/waterbox

**Comment by twodam** [comment]
PR to add page for creating new space https://github.com/nance-eth/nance-interface/pull/30

**Comment by jigglyjams** [comment]
https://flipsidecrypto.xyz/LittlerData/snapshot-xvqSdP



![Image](https://github.com/nance-eth/nance-interface/assets/83923290/c7ad7aac-f4ea-4a80-b45a-b3042f97758e)

**Comment by jigglyjams** [comment]
Bananapus govbot reminder deployed

**Comment by jigglyjams** [comment]
moving to done and we will make cards for individual clients that are more specific
