### ISSUE TITLE
Interface Optimizations

### ISSUE THREAD

**Issue by twodam** [nance-eth/nance-interface#90]
- [ ] Lazy loading
- [ ] Don't block too long
- [ ] Reduce/delay not-often-used requests
- [ ] Avoid re-rendering of not necessary components
- [x] Cache not-often-changed infos, e.g: space info, proposals in past cycles

**Comment by jigglyjams** [comment]
Caching proposal if its not editable
https://github.com/nance-eth/nance-interface/blob/e83c4df7c03dcb8d5b31b94ac40cf247ed579fda/pages/s/%5Bspace%5D/%5Bproposal%5D.tsx#L36C11-L36C11

**Comment by jigglyjams** [comment]
this should always be an ongoing effort no specific issue needed
