### ISSUE TITLE
Markdown sanitizing removes text before headings

### ISSUE THREAD

**Issue by jigglyjams** [nance-eth/nance-interface#92]
![Image](https://user-images.githubusercontent.com/83923290/266134553-e536c41c-6491-42be-91b7-9469cd385b69.jpeg)

Able to reproduce with 
https://nance.app/s/waterbox/1f2473ba8924429d9555683351eefe8b

See the [API call response](http://api.nance.app/waterbox/proposal/1f2473ba8924429d9555683351eefe8b) for full body text which contains the text before the first heading

It seems like the table of contents generator is removing it somehow
https://github.com/nance-eth/nance-interface/blob/main/components/MarkdownWithTOC.tsx

**Comment by twodam** [comment]
fixed by https://github.com/nance-eth/nance-interface/commit/12561e7f990dead02ce5e86b8d83649891643457
